version: '3'
services:
  
  app:    
    environment:
      APP_ENV: local
      APP_DEBUG: "true"          

  front-end:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: node:15
    container_name: front-end
    restart: unless-stopped
    tty: true
    environment:
      NODE_ENV: development 
    working_dir: /var/www/front
    volumes:
      - /var/www/front/node_modules
      - ./front/:/var/www/front      
    networks:
      - app-network      
  
  webserver:    
    depends_on: 
      - app      
      
    volumes:
      - ./back/:/var/www/back
      - ./front/:/var/www/front
      - ./nginx/dev/conf.d/:/etc/nginx/conf.d/