version: '3'
services:

  #PHP Service
  app:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      APP_ENV: local      
    working_dir: /var/www/back
    volumes:
      - /var/www/back/vendor
      - ./back/:/var/www/back
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network  

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - app      
    volumes:
      - ./back/:/var/www/back      
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/mysql-files:/var/lib/mysql-files
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
volumes:
  dbdata:
    driver: local
#Docker Networks
networks:
  app-network:
    driver: bridge